# Generated by Django 5.0.3 on 2024-03-31 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf',
            field=models.FileField(blank=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='thumb',
            field=models.ImageField(blank=True, default='default1.png', upload_to=''),
        ),
    ]
