# Generated by Django 5.0.3 on 2024-03-31 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_article_pdf_alter_article_thumb'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='email',
            field=models.EmailField(default='ishaanagarwal.uni@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='organization',
            field=models.CharField(default='MIT Manipal', max_length=255),
            preserve_default=False,
        ),
    ]
